#!/bin/sh

sudo apt install curl
sudo apt install libfuse2

# gets latest nvim
curl -LO https://github.com/neovim/neovim/releases/latest/download/nvim.appimage
chmod u+x nvim.appimage
./nvim.appimage
mv ./nvim/appimage /usr/bin/nvim

# gets packer for nvim
git clone --depth 1 https://github.com/wbthomason/packer.nvim\
 ~/.local/share/nvim/site/pack/packer/start/packer.nvim

