#!/bin/sh

# basics needed
sudo apt install curl libfuse2
sudo apt autoremove

# gets latest nvim
curl -LO https://github.com/neovim/neovim/releases/latest/download/nvim.appimage
chmod u+x nvim.appimage
sudo mv nvim/appimage /usr/bin/nvim

# gets packer for nvim
git clone --depth 1 https://github.com/wbthomason/packer.nvim\
 ~/.local/share/nvim/site/pack/packer/start/packer.nvim

# grabs node , needed for coc (lsp)
sudo curl -sL install-node.vercel.app/lts | sudo bash

echo "[-] Download fonts [-]"
echo "https://github.com/ryanoasis/nerd-fonts/releases/download/v2.3.3/Hack.zip"
wget https://github.com/ryanoasis/nerd-fonts/releases/download/v2.3.3/Hack.zip
unzip Hack.zip -d ~/.fonts
fc-cache -fv
echo "done!"
